# Check that this is where your pwsh.exe is.
set -g default-command 'exec "$(wslpath "$(cmd.exe /c "echo %LOCALAPPDATA%" 2>/dev/null | tr -d "\r")")/Microsoft/WindowsApps/pwsh.exe" -nologo -noexit -c sl'
