# Check that this is where your pwsh.exe is. cmd.exe is called by absolute path
# because the Windows entries are missing from $PATH when the server is started
# by the systemd user service.
set -g default-command 'exec "$(wslpath "$(/mnt/c/Windows/system32/cmd.exe /c "echo %LOCALAPPDATA%" 2>/dev/null | tr -d "\r")")/Microsoft/WindowsApps/pwsh.exe" -nologo -noexit -c sl'
